---
- hosts: localhost
  vars_files:
    - ./roles/group_vars/all.yaml
    - ./roles/group_vars/secret_file.yaml
  roles:
    - launch_ec2

- hosts: all
  roles:
    - {role: configure_instances, become: true}

- hosts: tag_Name_dbserver
  vars_files:
    - ./roles/group_vars/secret_file.yaml
    - ./roles/group_vars/all.yaml
  roles:
    - db_conf

- hosts: tag_Name_app
  roles:
    - app_conf
