---
- hosts: localhost
  vars_files:
    - ./roles/launch_ec2/vars/secret_file.yaml
    - ./roles/launch_ec2/vars/main.yaml
  roles:
    - launch_ec2

- hosts: all
  roles:
    - {role: configure_instances, become: true}

- hosts: tag_Name_dbserver
  vars_files:
    - ./roles/db_conf/vars/secret_file.yaml
    - ./roles/db_conf/vars/main.yaml
  roles:
    - db_conf

- hosts: tag_Name_app
  roles:
    - app_conf
