---
- name: copy init script for db on remote host
  copy:
    src: ~/project/python-postgres-user-registration/postgres/schema.sql
    dest: /home/ec2-user/postgres/
    owner: ec2-user
    group: ec2-user

- name: start postgres in container on remote host
  docker_container:
    name: postgres
    image: postgres:9.5
    env:
      POSTGRES_USER:     "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_pass }}"
      POSTGRES_DB:       "{{ db }}"
    recreate: yes
    exposed_ports:
      - 5432 
    ports:
      - "5432:5432"
    volumes: 
      - /home/ec2-user/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - /db:/var/lib/postgresql/data

- name: get postgres IP address
  command: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' postgres"
  register: db_ip_address

- name: wait while dbsever is RASKOCHEGARITSA
  wait_for:
    host: "{{ db_ip_address.stdout }}"
    port: 5432
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 30