---
- name: create rds instance
  community.aws.rds:
    command: create
    instance_name: "{{ db }}"
    db_name: "{{ db }}"
    db_engine: postgres
    engine_version: 9.6.20
    size: 10
    instance_type: db.t2.micro
    username: "{{ db_user }}"
    password: "{{ db_pass }}"
    backup_retention: 0
    port: 5432
    publicly_accessible: true
    subnet: default-vpc-d4f5aabc
    vpc_security_groups:
      - sg-0bad191055634fbfa
    aws_access_key: "{{ vault_access_key }}"
    aws_secret_key: "{{ vault_secret_key }}"
    region: "{{ aws_region }}"
    wait: true
    wait_timeout: 600

- name: Get facts about an instance
  community.aws.rds:
    command: facts
    instance_name: "{{ db }}"
    aws_access_key: "{{ vault_access_key }}"
    aws_secret_key: "{{ vault_secret_key }}"
    region: "{{ aws_region }}"
  register: info

- name: execute script
  command: "psql {{ db }} -p 5432 -h {{ info.instance.endpoint }}
            -f  ~/project/python-postgres-user-registration/postgres/schema.sql
            -U postgres"
  environment:
    PGPASSWORD: '{{db_pass}}'
  register: sql_response

- name: Change app.py to create right Docker image
  lineinfile:
    path: ~/project/python-postgres-user-registration/app.py
    regexp: ', host=\"'
    line: 'Database.initialise(database="{{ db }}", user="{{ db_user }}",
           password="{{ db_pass }}", host="{{ item }}")'
  with_items:
    - "{{ info.instance.endpoint }}"
  register: image

- name: Build/push image
  docker_image:
    name: dvolnistiy/postgres-user-registration
    build:
      path: ~/project/python-postgres-user-registration
      nocache: true
    state: present
    force_source: true
    source: build
    push: true
  when: image.changed
