---
- name: Delete rds instance
  rds_instance:
    state: absent
    db_instance_identifier: "{{ db }}"
    #instance_name: "{{ db }}"
    skip_final_snapshot: true
    aws_access_key: "{{ vault_access_key }}"
    aws_secret_key: "{{ vault_secret_key }}"
    region: "{{ aws_region }}"
    wait: true

- name: Stop EC2 instance to get it id
  ec2:
    instance_tags:
      class: application
    state: stopped
    aws_access_key: "{{ vault_access_key }}"
    aws_secret_key: "{{ vault_secret_key }}"
    region: "{{ aws_region }}"
    wait: true
  register: F

- name: Destroy EC2 instance
  ec2:
    state: absent
    instance_ids: "{{ F.instance_ids }}"
    aws_access_key: "{{ vault_access_key }}"
    aws_secret_key: "{{ vault_secret_key }}"
    region: "{{ aws_region }}"
    wait: true
  when: F.changed
  
- name: Get container_instance
  shell: "aws ecs list-container-instances --cluster {{ ecs_cluster_name }} | grep /{{ ecs_cluster_name }}/"
  register: info
  ignore_errors: true

- name: Deregister container_instance from ECS
  command: "aws ecs deregister-container-instance --cluster {{ ecs_cluster_name }} --container-instance {{ info.stdout }}"
  ignore_errors: true

- name: Destroy cluster
  ecs_cluster:
    name: "{{ ecs_cluster_name }}"
    state: absent
    aws_access_key: "{{ vault_access_key }}"
    aws_secret_key: "{{ vault_secret_key }}"
    region: "{{ aws_region }}"
